### ISSUE TITLE
[BUG] Numbers in the millions

### ISSUE THREAD

**Issue by yawboakye** [niisign/intro_to_programming#2]
@niisign There's a bug that in the code that produces results like this for numbers in the millions:

``` shell
$ ./fiw.rb
Please enter a number
8000000
Eight million Seven million Six million Five million Four million Three million Two million One million Zero
```

**Comment by niisign** [comment]
Yes sir will correct it. Pardon me.

**Comment by yawboakye** [comment]
I think the bug on this [line](https://github.com/niisign/intro_to_programming/blob/ece459dcb0aae00cbe9b598329366c88774b9a14/092716/fiw.rb#L74). How you're reducing the number is wrong.
